# Generated by Django 5.0.2 on 2024-02-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='My Hospital', max_length=200)),
                ('contact_number', models.IntegerField(blank=True, default='123456789')),
                ('contact_email', models.EmailField(default='HospitalEmail@email.com', max_length=254)),
                ('contact_address', models.TextField(default='1-2-3,Avenue Road,Straight Way Street,Patny City,786588')),
                ('headliner_1', models.CharField(default='We Provide Medical Services That You Can Trust!', max_length=200)),
                ('headline_1_tagline', models.CharField(default='Add any tag line which is suiltable for background image and headline', max_length=200)),
                ('headliner_2', models.CharField(default='We Provide Medical Services That You Can Trust!', max_length=200)),
                ('headline_2_tagline', models.CharField(default='Add any tag line which is suiltable for background image and headline', max_length=200)),
                ('headliner_3', models.CharField(default='We Provide Medical Services That You Can Trust!', max_length=200)),
                ('headline_3_tagline', models.CharField(default='Add any tag line which is suiltable for background image and headline', max_length=200)),
                ('scheduler_1', models.CharField(default='Emergency Cases', max_length=200)),
                ('scheduler_1_tagline', models.TextField(default='Emergency cases demand swifrequire rapid triage, assessment, and treatment by a skilled team. Swift diagnosis, tailored interventions, and continuous monitoring ensure effective management. Clear communication with patients and documentation of care are crucial for optimal outcomes.')),
                ('scheduler_2', models.CharField(default='Doctors Availability', max_length=200)),
                ('scheduler_2_tagline', models.TextField(default='Hospitals schedule rotating shifts to ensure doctors are available round-the-clock. On-call systems facilitate access to specialists for consultations or emergencies outside regular hours. Strategic planning ensures balanced staffing for timely and comprehensive medical care.')),
                ('scheduler_3', models.CharField(default='Working Hours!', max_length=200)),
                ('scheduler_3_tagline', models.TextField(default="<li class='day'>Monday<span>9AM - 6PM</span></li><li class='day'>Tuesday<span>9AM - 6PM</span></li><li class='day'>Wednesday<span>9AM - 6PM</span></li><li class='day'>Thursday<span>9AM - 6PM</span></li><li class='day'>Firday<span>9AM - 6PM</span></li><li class='day'>Saturday<span>9AM - 6PM</span></li><li class='day'>Sunday <span>9AM - 12PM</span></li>")),
                ('emergency_call_header', models.TextField(default='Do you need Emergency Medical Care? Call @')),
                ('emergency_call_tagline', models.TextField(default='We ensure immediate response to critical situations, providing life-saving interventions and rapid transport to healthcare facilities. Highly trained professionals deliver urgent medical assistance, prioritizing patient stabilization and timely treatment.')),
                ('cleanliness_header', models.TextField(default='We Maintain Cleanliness Rules Inside Our Hospital')),
                ('cleanliness_tagline', models.TextField(default='Our Hospital cleanliness is upheld through rigorous disinfection protocols and strict hand hygiene measures. Continuous monitoring ensures a safe and hygienic environment for patients and staff.')),
            ],
        ),
    ]
