# Generated by Django 5.0.2 on 2024-02-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmt_main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(blank=True, default=None, max_length=100)),
                ('qualification', models.CharField(blank=True, default=None, max_length=100)),
                ('specialization', models.CharField(blank=True, default=None, max_length=100)),
                ('available_timings', models.TextField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, default=None, max_length=100)),
                ('description', models.TextField(blank=True, default=None)),
                ('fee', models.IntegerField(blank=True, default=None)),
            ],
        ),
        migrations.AddField(
            model_name='hospitaldetail',
            name='about_us',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='hospitaldetail',
            name='contact_address',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='hospitaldetail',
            name='contact_number',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='hospitaldetail',
            name='email_address',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='hospitaldetail',
            name='established_on',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='hospitaldetail',
            name='hospital_rooms',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='hospitaldetail',
            name='learn_more',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='hospitaldetail',
            name='opening_hours',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='hospitaldetail',
            name='promotions',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='hospitaldetail',
            name='specialization',
            field=models.TextField(blank=True, default=None),
        ),
    ]
