# Generated by Django 5.0.2 on 2024-02-27 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmt_main_app', '0003_dicty_homepage_keyval_delete_doctorsdetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='My Hospital', max_length=200)),
                ('headliner_1', models.CharField(default='We Provide Medical Services That You Can Trust!', max_length=200)),
                ('headline_1_tagline', models.CharField(default='Add any tag line which is suiltable for background image and headline', max_length=200)),
                ('headliner_2', models.CharField(default='We Provide Medical Services That You Can Trust!', max_length=200)),
                ('headline_2_tagline', models.CharField(default='Add any tag line which is suiltable for background image and headline', max_length=200)),
                ('headliner_3', models.CharField(default='We Provide Medical Services That You Can Trust!', max_length=200)),
                ('headline_3_tagline', models.CharField(default='Add any tag line which is suiltable for background image and headline', max_length=200)),
                ('scheduler_1', models.CharField(default='Emergency Cases', max_length=200)),
                ('scheduler_1_tagline', models.TextField(default='Emergency cases demand swifrequire rapid triage, assessment, and treatment by a skilled team. Swift diagnosis, tailored interventions, and continuous monitoring ensure effective management. Clear communication with patients and documentation of care are crucial for optimal outcomes.')),
                ('scheduler_2', models.CharField(default='Doctors Availability', max_length=200)),
                ('scheduler_2_tagline', models.TextField(default='Hospitals schedule rotating shifts to ensure doctors are available round-the-clock. On-call systems facilitate access to specialists for consultations or emergencies outside regular hours. Strategic planning ensures balanced staffing for timely and comprehensive medical care.')),
                ('scheduler_3', models.CharField(default='Working Hours!', max_length=200)),
                ('scheduler_3_tagline', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
        migrations.AlterField(
            model_name='keyval',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmt_main_app.homepages'),
        ),
        migrations.DeleteModel(
            name='Dicty',
        ),
    ]
