# Generated by Django 5.0.2 on 2024-02-27 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmt_main_app', '0004_homepages_delete_homepage_alter_keyval_container_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePages',
            new_name='HomePage',
        ),
        migrations.DeleteModel(
            name='KeyVal',
        ),
    ]
