# Generated by Django 5.0.2 on 2024-02-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmt_main_app', '0006_homepage_cleanliness_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_number',
            field=models.IntegerField(blank=True, default='123456789'),
        ),
    ]
